import * as icons from './icons/index.js'
import { createStyledIcon as wrap } from './components'

export const IconAlert = wrap(icons.IconAlert)
export const IconArrowDown = wrap(icons.IconArrowDown)
export const IconArrowLeft = wrap(icons.IconArrowLeft)
export const IconArrowRight = wrap(icons.IconArrowRight)
export const IconArrowUp = wrap(icons.IconArrowUp)
export const IconBuilding = wrap(icons.IconBuilding)
export const IconCheck = wrap(icons.IconCheck)
export const IconChevronDown = wrap(icons.IconChevronDown)
export const IconChevronLeft = wrap(icons.IconChevronLeft)
export const IconChevronRight = wrap(icons.IconChevronRight)
export const IconChevronUp = wrap(icons.IconChevronUp)
export const IconClock = wrap(icons.IconClock)
export const IconClose = wrap(icons.IconClose)
export const IconDocument = wrap(icons.IconDocument)
export const IconGlobe = wrap(icons.IconGlobe)
export const IconInfo = wrap(icons.IconInfo)
export const IconLocation = wrap(icons.IconLocation)
export const IconMail = wrap(icons.IconMail)
export const IconPencil = wrap(icons.IconPencil)
export const IconPhone = wrap(icons.IconPhone)
export const IconSearch = wrap(icons.IconSearch)
export const IconCalendar = wrap(icons.IconCalendar)
export const IconAccessibility = wrap(icons.IconAccessibility)
export const IconArchive = wrap(icons.IconArchive)
export const IconCaution = wrap(icons.IconCaution)
export const IconWIP = wrap(icons.IconWIP)
export const IconChart = wrap(icons.IconChart)
export const IconQuestion = wrap(icons.IconQuestion)
export const IconHamburgerButton = wrap(icons.IconHamburgerButton)
export const IconMinus = wrap(icons.IconMinus)
export const IconPlus = wrap(icons.IconPlus)
