
import * as icons from '@sfgov/icons/react'
import { createStyledIcon as wrap } from './components'

export const IconAccessibility = wrap(icons.IconAccessibility, [0, 0, 20, 20])
export const IconAlert = wrap(icons.IconAlert, [0, 0, 20, 20])
export const IconArchive = wrap(icons.IconArchive, [0, 0, 20, 20])
export const IconArrowDown = wrap(icons.IconArrowDown, [0, 0, 20, 20])
export const IconArrowLeft = wrap(icons.IconArrowLeft, [0, 0, 20, 20])
export const IconArrowRight = wrap(icons.IconArrowRight, [0, 0, 20, 20])
export const IconArrowUp = wrap(icons.IconArrowUp, [0, 0, 20, 20])
export const IconBuilding = wrap(icons.IconBuilding, [0, 0, 20, 20])
export const IconCalendar = wrap(icons.IconCalendar, [0, 0, 20, 20])
export const IconCaution = wrap(icons.IconCaution, [0, 0, 20, 20])
export const IconChart = wrap(icons.IconChart, [0, 0, 20, 20])
export const IconCheck = wrap(icons.IconCheck, [0, 0, 20, 20])
export const IconChevronDown = wrap(icons.IconChevronDown, [0, 0, 20, 20])
export const IconChevronLeft = wrap(icons.IconChevronLeft, [0, 0, 20, 20])
export const IconChevronRight = wrap(icons.IconChevronRight, [0, 0, 20, 20])
export const IconChevronUp = wrap(icons.IconChevronUp, [0, 0, 20, 20])
export const IconClock = wrap(icons.IconClock, [0, 0, 20, 20])
export const IconClose = wrap(icons.IconClose, [0, 0, 20, 20])
export const IconDocument = wrap(icons.IconDocument, [0, 0, 20, 20])
export const IconGlobe = wrap(icons.IconGlobe, [0, 0, 20, 20])
export const IconHamburgerButton = wrap(icons.IconHamburgerButton, [0, 0, 20, 20])
export const IconInfo = wrap(icons.IconInfo, [0, 0, 20, 20])
export const IconLocation = wrap(icons.IconLocation, [0, 0, 20, 20])
export const IconMail = wrap(icons.IconMail, [0, 0, 20, 20])
export const IconMinus = wrap(icons.IconMinus, [0, 0, 19, 19])
export const IconPencil = wrap(icons.IconPencil, [0, 0, 20, 20])
export const IconPhone = wrap(icons.IconPhone, [0, 0, 20, 20])
export const IconPlus = wrap(icons.IconPlus, [0, 0, 19, 19])
export const IconQuestion = wrap(icons.IconQuestion, [0, 0, 20, 20])
export const IconSearch = wrap(icons.IconSearch, [0, 0, 20, 20])
export const IconWIP = wrap(icons.IconWIP, [0, 0, 20, 20])
