
import * as icons from '@sfgov/icons/react'
import { createStyledIcon as wrap } from '../src/components/SVGIcon'

export const IconAccessibility = wrap(icons.IconAccessibility, { width: 20, height: 20 })
export const IconAlert = wrap(icons.IconAlert, { width: 20, height: 20 })
export const IconArchive = wrap(icons.IconArchive, { width: 20, height: 20 })
export const IconArrowDown = wrap(icons.IconArrowDown, { width: 20, height: 20 })
export const IconArrowLeft = wrap(icons.IconArrowLeft, { width: 20, height: 20 })
export const IconArrowRight = wrap(icons.IconArrowRight, { width: 20, height: 20 })
export const IconArrowUp = wrap(icons.IconArrowUp, { width: 20, height: 20 })
export const IconBuilding = wrap(icons.IconBuilding, { width: 20, height: 20 })
export const IconCalendar = wrap(icons.IconCalendar, { width: 20, height: 19.75 })
export const IconCaution = wrap(icons.IconCaution, { width: 20, height: 20 })
export const IconChart = wrap(icons.IconChart, { width: 20, height: 20 })
export const IconCheck = wrap(icons.IconCheck, { width: 20, height: 20 })
export const IconChevronDown = wrap(icons.IconChevronDown, { width: 20, height: 20 })
export const IconChevronLeft = wrap(icons.IconChevronLeft, { width: 20, height: 20 })
export const IconChevronRight = wrap(icons.IconChevronRight, { width: 20, height: 20 })
export const IconChevronUp = wrap(icons.IconChevronUp, { width: 20, height: 20 })
export const IconClock = wrap(icons.IconClock, { width: 20, height: 20 })
export const IconClose = wrap(icons.IconClose, { width: 20, height: 20 })
export const IconDocument = wrap(icons.IconDocument, { width: 20, height: 20 })
export const IconGlobe = wrap(icons.IconGlobe, { width: 20, height: 20 })
export const IconHamburgerButton = wrap(icons.IconHamburgerButton, { width: 20, height: 20 })
export const IconInfo = wrap(icons.IconInfo, { width: 20, height: 20 })
export const IconLocation = wrap(icons.IconLocation, { width: 20, height: 20 })
export const IconMail = wrap(icons.IconMail, { width: 20, height: 20 })
export const IconMinus = wrap(icons.IconMinus, { width: 19, height: 19 })
export const IconPencil = wrap(icons.IconPencil, { width: 20, height: 20 })
export const IconPhone = wrap(icons.IconPhone, { width: 20, height: 20 })
export const IconPlus = wrap(icons.IconPlus, { width: 19, height: 19 })
export const IconQuestion = wrap(icons.IconQuestion, { width: 20, height: 20 })
export const IconSearch = wrap(icons.IconSearch, { width: 20, height: 20 })
export const IconWIP = wrap(icons.IconWIP, { width: 20, height: 20 })
