#!/bin/bash
dir=${1:-dist/css/files}
mkdir -p $dir
cp \
  node_modules/@fontsource/rubik/files/rubik-latin-{300,400,500}-normal.woff* \
  node_modules/@fontsource/noto-sans-tc/files/noto-sans-tc-chinese-traditional-{300,400,500}-normal.woff* \
  node_modules/@fontsource/roboto-mono/files/roboto-mono-latin-300-normal.woff* \
  $dir

