default: false
heading-increment: true
heading-style:
  style: atx
first-heading-h1:
  level: 2
front-matter:
  required_keys:
    - title
line-length: false
links: true
list-indent: true
no-bare-urls: false
no-empty: true
ul-indent:
  indent: 2
  start_indented: false
ul-style:
  style: consistent
whitespace: true
