name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm

      - run: npm install
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: npm run lint

      # this sets NODE_ENV=production for all of the build scripts
      - run: echo NODE_ENV=production >> $GITHUB_ENV
      - run: npm run build:ci

      - uses: primer/publish@v3
        with:
          default_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
