name: CI
on:
  - push
  - delete

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm

      - run: npm ci
      - run: npm run lint

      # this sets NODE_ENV=production for all of the build scripts
      # (`npm ci` doesn't install anything if it's set earlier)
      - name: set up node and npm environments
        run: |
          echo NODE_ENV=production >> $GITHUB_ENV
          echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > $HOME/.npmrc

      # run these separately so that it's easier to see what failed
      - run: npm run build-assets
      - run: npm run build-docs

      # run pre-publish checks
      - run: npm run prepublishOnly

      - uses: primer/publish@v3.0.0
        id: publish
        with:
          npm_args: --unsafe-perm
          default_branch: main
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: set BRANCH_DIST_TAG
        if: github.ref_type == 'branch'
        run: echo "BRANCH_DIST_TAG=branch.${{ github.ref_name }}" >> $GITHUB_ENV

      - name: npm dist-tag add
        if: steps.publish.conclusion == 'success' && env.BRANCH_DIST_TAG
        run: |
          CURRENT=$(node -e 'const { name, version } = require("./package.json"); console.log(`${name}@${version}`)')
          npm dist-tag add "$CURRENT" "$BRANCH_DIST_TAG"

      - name: npm dist-tag rm
        if: github.event_name == 'delete' && env.BRANCH_DIST_TAG
        run: |
          npm dist-tag rm "$BRANCH_DIST_TAG"
