name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          npm-version: '8.x'
          cache: npm

      - run: npm install
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: npm run lint

      # this sets NODE_ENV=production for all of the build scripts
      - run: echo NODE_ENV=production >> $GITHUB_ENV
      # run these separately so that it's easier to see what failed
      - run: npm run build
      # run pre-publish checks
      - run: npm run prepublishOnly

      - uses: primer/publish@v3.0.0
        with:
          npm_args: --unsafe-perm --allow-same-version
          default_branch: main
          dir: packages/sfgov-design-system
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
