name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: npm

      - run: npm install
      - run: npm run lint

      # this sets NODE_ENV=production for all of the build scripts
      # (`npm ci` doesn't install anything if it's set earlier)
      - run: |
          echo NODE_ENV=production >> $GITHUB_ENV

      # run these separately so that it's easier to see what failed
      - run: npm run build-assets
      - run: npm run build-docs

      # run pre-publish checks
      - run: npm run prepublishOnly

      - uses: primer/publish@v3.0.0
        with:
          npm_args: --unsafe-perm --allow-same-version
          default_branch: main
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
