name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm

      - run: npm install
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: npx lerna run lint

      # this sets NODE_ENV=production for all of the build scripts
      - run: echo NODE_ENV=production >> $GITHUB_ENV

      - run: npm run build -w sfgov-design-system
      - run: npm run build -w @sfgov/icons
      - run: npm run build -w @sfgov/react
      - run: echo "NPM_AUTH_TOKEN=${{ secrets.NPM_AUTH_TOKEN }}" >> $GITHUB_ENV
      - if: github.ref == 'refs/heads/main'
        run: lerna publish --yes
        id: publishMain
      - if: startsWith(github.ref, 'refs/heads/release-')
        run: lerna publish --yes prerelease --dist-tag pre
        id: publishPre
      - if: ${{ !steps.publishMain && !steps.publishPre }}
        run: lerna publish --yes --canary --dist-tag canary
