name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm

      - run: npm install
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: npx lerna run lint

      # this sets NODE_ENV=production for all of the build scripts
      - run: echo NODE_ENV=production >> $GITHUB_ENV

      - run: npm run build -w sfgov-design-system
      - run: npm run prepublishOnly -w sfgov-design-system
      - uses: primer/publish@v3.0.0
        with:
          default_branch: main
          dir: packages/sfgov-design-system
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: npm run build -w @sfgov/react
      - uses: primer/publish@v3.0.0
        with:
          default_branch: main
          dir: packages/react
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: npm run build -w @sfgov/icons
      - uses: primer/publish@v3.0.0
        with:
          default_branch: main
          dir: packages/icons
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
