name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm

      - run: npm install --exclude=prod --include=optional --no-fund
      - run: npm install --include=dev --include=optional --no-fund

      - run: npm run lint

      # build the design system
      - run: npm run ci:build

      # run pre-publish checks
      - run: npm run prepublishOnly -w sfgov-design-system --if-present

      - uses: primer/publish@v3.0.0
        with:
          npm_args: --allow-same-version
          default_branch: main
          dir: packages/sfgov-design-system
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
