on: delete

jobs:
  delete-dist-tag:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - env:
          DIST_TAG: branch/${{ github.ref_name }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm dist-tag rm "$(npm info . name)@$DIST_TAG" || \
            echo "Unable to delete npm dist-tag '$DIST_TAG'"
