name: Reports
on: [pull_request]

jobs:
  reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ github.token }}
          pattern: '{css,elements,icons,react}/**/*.{css,js,mjs,svg}'
          exclude: '*/src/**'
          build-script: 'build:ci'
