name: Reports
on: [pull_request]

jobs:
  reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ github.token }}
          pattern: 'packages/*/dist/**/*.{js,mjs,css,svg}'
          build-script: 'build:ci'
